version: "3.7"
services:
  db:
    image: "mysql"
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${MAINDB_NAME}
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    container_name: typeorm-mysql
    command: --default-authentication-plugin=mysql_native_password

  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    restart: always
    volumes:
      - ./src:/home/node/app/src
    container_name: ts-node-docker
    expose:
      - 5000
    ports:
      - 5000:5000
    depends_on:
      - db
    command:
      - bash
      - -c
      - |
        chmod +x /wait-for-it.sh
        /wait-for-it.sh db:3306 -t 10
        yarn dev

volumes:
  data:
