version: "3.7"

services:
  db:
    environment:
      - MYSQL_DATABASE=${TESTDB_NAME}
  ts-node-docker:
    command:
      - bash
      - -c
      - |
        chmod +x /wait-for-it.sh
        /wait-for-it.sh db:3306 -t 10
        yarn test
        exit
